# Generated by Django 3.0.1 on 2023-05-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_bananas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bananas',
            name='date',
            field=models.CharField(default='2023-01-01-00-00-00', max_length=200),
        ),
    ]
